---
- name: Retrieve Interface Status
  hosts: all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: False

  tasks:
    - name: Get Junos Device Information
      juniper_junos_config:
        user: "root"
        passwd: "Juniper"
        timeout: 240

        load: merge
        format: 'set'
        confirmed: 10

        lines:
          - 'set system host-name qfx-5100-aa'
          - 'set system domain-name google.com'
          - 'set protocols lldp interface all'

      # save the output by register keyword into cmd_output  
      register: result

    - name: "Print result"
      debug:
        var: result.diff_lines
      when: result.diff_lines is defined
      